apiVersion: apps/v1
kind: Deployment

# Deployment 기본 정보
metadata:
  name: spring-deployment # Deployment 의 이름

# Deployment 세부 정보
spec:
  replicas: 3 # pod 몇개 생성할 지
  selector: # 어떤 Pod 를 배포할 것인지
    matchLabels:
      app: backend-app # "backend-app" 이라는 label 과 일치(match) 하는 Pod를 기반으로 Deployment 를 생성하겠다.

  # 배포할 Pod 정의
  template:
    metadata:
      labels: # label 붙여준다고 생각
        app: backend-app
    spec: # Pod 에 대한 Spec 작성
      containers:
        - name: spring-container
          image: spring-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MY_ACCOUNT
              valueFrom:
                configMapKeyRef:
                  name: spring-config # ConfigMap의 이름 (spring-config 라는 이름의 ConfigMap 에서)
                  key: my-account # ConfigMap에 설정되어 있는 Key값 (my-account 라는 key 에 해당하는 value 로 넣겠다.)
            - name: MY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-secret
                  key: my-password
            - name: DB_HOST
              value: mysql-service # Service의 name만 입력하면 다른 서비스와 통신할 수 있다.
            - name: DB_PORT
              value: "3306" # 숫자값을 문자로 인식하게 만들기 위해 쌍따옴표 붙여야 한다.
            - name: DB_NAME
              value: kub-practice
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: password123