apiVersion: apps/v1
kind: Deployment

# Deployment 기본 정보
metadata:
  name: spring-deployment # Deployment 의 이름

# Deployment 세부 정보
spec:
  replicas: 3 # pod 몇개 생성할 지
  selector: # 어떤 Pod 를 배포할 것인지
    matchLabels:
      app: backend-app # "backend-app" 이라는 label 과 일치(match) 하는 Pod를 기반으로 Deployment 를 생성하겠다.

  # 배포할 Pod 정의
  template:
    metadata:
      labels: # label 붙여준다고 생각
        app: backend-app
    spec: # Pod 에 대한 Spec 작성
      containers:
        - name: spring-container
          image: spring-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MY_ACCOUNT
              value: kim
            - name: MY_PASSWORD
              value: pwd1234
